name: OGP Builder

on:
  push:
    branches: master

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - uses: actions/checkout@v2
        with:
          ref: ${{ steps.extract_branch.outputs.branch }}
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn install --frozen-lockfile
      - run: yarn run test
      - run: yarn run generate
      - run: pip3 install selenium
      - run: (python3 -m http.server --directory ./dist 8000 &)  ; python3 ./ui-test/ogp-screenshot.py
      - name: Upload screenshot
        uses: actions/upload-artifact@v1
        with:
          name: ogp
          path: ogp
  upload:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ steps.extract_branch.outputs.branch }}
      - name: Download ogp images
        uses: actions/download-artifact@v1
        with:
          name: ogp
      - name: Commit files
        env:
          github_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git pull https://x-access-token:${github_token}@github.com/codeforsapporo/covid19 development
          cp -rp ogp static/
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add static/ogp
          git commit -m "OGP Update"
      - name: Push changes
        env:
          github_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push https://x-access-token:${github_token}@github.com/codeforsapporo/covid19 development
          
